# Generated by Django 3.0.3 on 2020-02-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200214_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
